# Generated by Django 4.1.1 on 2022-09-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_books_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
