# Generated by Django 4.1.1 on 2022-09-23 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_books_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.CharField(default='UNKNOWN', max_length=10000),
        ),
        migrations.AlterField(
            model_name='books',
            name='addtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
