# Generated by Django 4.1.1 on 2022-09-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_books_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(default='-', max_length=10000),
        ),
    ]
